### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by giangdao1402** [sparolab/Referee#2]
Hi @hogyun2 @Refstop 
Thank for your great work
I just wanna ask that can you give evaluation code or at least threshold of similarity and translation for me to evaluate this algorithm
Thank you !

**Comment by hogyun2** [comment]
I appreciate your interest!

Do you mean the threshold that makes precision 100%?

**Comment by giangdao1402** [comment]
Thanks but i don't quite understand what you said
I mean this threshold
<img width="444" alt="Ảnh màn hình 2024-08-08 lúc 12 39 51" src="https://github.com/user-attachments/assets/a2c2cc63-4404-432f-a327-351b8e15eb3a">

**Comment by hogyun2** [comment]
You can use the threshold between 0 and 1.
If the threshold is low, more loops are detected but false loops together.
If the threshold is high, fewer loops are detected but false loops are almost removed.
Also, a precision-recall curve is finally created by varying these thresholds several times.
If you plan to do a SLAM experiment, I recommend 0.8~0.9.

**Comment by giangdao1402** [comment]
Thank you !
